/* ─────────────────────────────────────────────────────────────
   THE MONTH'S CONTENT.
   Next month: edit this one file, re-upload the folder. Nothing
   else changes — the link, the ticks and the notes all stay put.
   ───────────────────────────────────────────────────────────── */

/* label = what the header shows.  start/end = the real dates, used to draw the
   calendar.  storeKey = change it and next month starts with empty tick boxes. */
window.PLAN_META = {
  label: "15 Sept – 14 Oct",
  start: "2026-09-15",
  end:   "2026-10-14",
  storeKey: "sep15"
};

window.PLAN = [
{w:1,head:"Week 1",sub:"15 – 21 Sept",note:"Your introduction. Two of these carry your voice for the first time.",
 shoot:"<b>Sat 13 Sept</b> — one block before launch covers Friday, Saturday and Sunday. Tuesday's reel is already filmed.",posts:[
 {id:"r1",date:"Tue 15",type:"REEL",series:"6AM 01",vo:true,film:"filmed 11 Sept",edit:"12–14 Sept",
  title:"The 6am morning — her introduction",
  what:"The morning ritual film with your voice over the top. Around 40 seconds.",
  steps:["Already filmed. Nothing to shoot.","<b>Record the voiceover at home</b>, phone close to your mouth, quietest room. Sit down, don't stand.","Read it slowly, like you're telling one person. Record it <b>five or six times</b> — we pick the best, so there's no bad take."],
  say:"I'm Swatti. Two kids, one very early alarm, and a city that never really slows down. For years I made the mornings beautiful for everybody else. The breakfast, the school run, the whole house put back together before anyone noticed it had come apart. Nobody was making them beautiful for me. So this is where that changes. Same early alarm, same city, same two kids. Just done properly this time, and slowly enough that I actually get to enjoy it. Strong body. Soft life. Come with me.",
  note:"Ends on the line already in your bio: <b>Strong body. Soft life.</b> That line becomes the thing people know you for, so it goes on the very first post."},
 {id:"c1",date:"Wed 16",type:"CAROUSEL",series:"Who she is",film:"photos by 13 Sept",edit:"14 Sept",
  title:"Nine things about me",
  what:"Eight photos already on your phone. Nothing to shoot.",
  steps:["Send Prince <b>eight photos you already love</b> — the horse, a Dubai evening, India, your coffee, a corner of your home, your drawing, your perfumes, one of you.","That's the whole job. We build the post and write the list."],
  note:"The caption is the real post. One page we studied grew to 67,000 followers in two months on almost nothing else — nice pictures, and the value written underneath."},
 {id:"r2",date:"Fri 18",type:"REEL",series:"Soft Life Notes 01",film:"Sat 13 Sept",edit:"15–17 Sept",
  title:"The boring thing, every day",
  what:"Quiet footage of you resetting the living room, one line of text over it.",
  steps:["Phone on the tripod in the corner, whole room in frame. <b>Folding a throw, straightening cushions.</b> 15 seconds.","Phone in hand, close: <b>watering or wiping a plant's leaves</b>. 10 seconds.","Close on your hands <b>lighting a candle</b>. 8 seconds.","Step back, the finished room, still and quiet. 8 seconds.","<b>No music while filming.</b> We want the real sound."],
  say:"nobody tells you the 'soft life' is mostly just doing the boring thing every single day, before anyone else is awake.",
  note:"That line sits at the top of the screen the whole video — the format from the two reels you sent."},
 {id:"r3",date:"Sat 19",type:"REEL",series:"Getting Ready 01",vo:true,film:"Sat 13 Sept",edit:"15–17 Sept",
  title:"Getting ready — what this page is for",
  what:"Your second voiceover reel. Getting dressed, while your voice explains what the page is for. 30 to 40 seconds.",
  steps:["Tripod facing the wardrobe. <b>Open it, take one outfit out.</b> 10 seconds.","The outfit <b>hanging on its own</b>, still. 6 seconds.","Close on your hands <b>putting jewellery on</b>. 8 seconds.","<b>Spray perfume with the light behind it</b> so the mist shows. Film it three or four times — it's the shot people stop for. 6 seconds.","You in the mirror, dressed, adjusting something. Face can be in this one. 8 seconds.","From behind — <b>walking out, closing the door</b>. 6 seconds.","Record the voiceover at home afterwards."],
  say:"This isn't a page about having a perfect life. It's about getting one per cent better every day and still enjoying the beautiful bits while you do it. Beauty, wellness, a home you actually want to be in — and being strong enough to carry all of it.",
  note:"After this you've introduced yourself twice and never once spoken to camera. That's the whole point of doing it this way."},
 {id:"r4",date:"Sun 20",type:"REEL",series:"6AM 02",film:"Sat 13 Sept",edit:"16–18 Sept",
  title:"Sunday reset",
  what:"The home reset. Real sound only, no talking, no music.",
  steps:["Close on <b>water going into a plant</b>. Get the sound. 10 seconds.","<b>Trimming flowers into a vase.</b> 15 seconds.","Coffee — <b>kettle, pour, stir.</b> Close, sound recording. 15 seconds.","<b>Folding laundry</b>, phone on the tripod. 12 seconds.","Finish on the tidy room, candle lit. 8 seconds."],
  note:"<b>Sound on, nothing playing in the background.</b> The pouring, the trimming, the folding — that sound is why these get watched twice."}]},

{w:2,head:"Week 2",sub:"22 – 28 Sept",note:"The course goes on the page. That becomes the backbone of the account.",
 shoot:"<b>Thu 17 Sept</b> — course morning, grab the studio footage. <b>Sat 19 Sept</b> — main block, about two hours.",posts:[
 {id:"r5",date:"Tue 22",type:"REEL",series:"Studio Days 01",film:"Thu 17 Sept",edit:"19–21 Sept",
  title:"Interior design school, week one",
  what:"The course, filmed as it happens. You're going anyway — just film it.",
  steps:["Before you leave: <b>notebook, pencils and bag laid out.</b> 8 seconds.","From the driver's seat — <b>the road ahead.</b> 10 seconds.","<b>Walking into the building.</b> Phone low, just walk. 8 seconds.","Close on <b>your hands opening the notebook</b> to a blank page. 8 seconds.","<b>Your hand sketching.</b> This one matters — film it twice. 15 seconds.","Coffee on the desk next to the work. 6 seconds."],
  say:"6 months of interior design school. with two kids at home.",
  note:"A <b>milestone</b> post, and on every page we studied milestones beat ordinary days by a mile. It's also a promise there's a story to follow — which is what makes people follow instead of just liking."},
 {id:"c2",date:"Wed 23",type:"CAROUSEL",series:"Interiors",film:"photos by 19 Sept",edit:"21 Sept",
  title:"Five details that make a room look expensive",
  what:"Photos of corners of your own home. The list in the caption is the real post.",
  steps:["Photograph <b>five corners of your home</b> you're proud of. Daylight, no flash.","If you've saved any interiors pictures you love, send those too."],
  note:"People save this kind of post, Instagram reads that as valuable, and it keeps surfacing for weeks. The one type that keeps working long after you post it."},
 {id:"r6",date:"Fri 25",type:"REEL",series:"Soft Life Notes 02",film:"Sat 19 Sept",edit:"22–24 Sept",
  title:"Rest, scheduled",
  what:"Coffee and drawing in the morning light, one line of text over it.",
  steps:["Tripod by the window. <b>You sitting down with coffee and your sketchbook.</b> 12 seconds.","Close on <b>your hand drawing.</b> 12 seconds.","Close on <b>the cup, steam in the light.</b> 8 seconds.","Your feet up, the quiet room. 6 seconds."],
  say:"i used to think rest had to be earned. now i put it in the calendar like a meeting.",
  note:"Lines like this get shared into people's stories. That's how an account with 1,000 followers reaches 50,000 — not through the video, through the sentence."},
 {id:"r7",date:"Sat 26",type:"REEL",series:"Getting Ready 02",film:"Sat 19 Sept",edit:"22–24 Sept",
  title:"Skincare, in order",
  what:"Your real routine. Hands, bottles, texture, mirror. No face needed.",
  steps:["<b>Products lined up on the shelf.</b> 8 seconds.","Each step, <b>close on your hands</b> — cleanser, serum, moisturiser. 8 seconds each.","One very close shot of <b>the cream's texture on your fingers.</b> 6 seconds.","Last shot in the mirror, skin finished. 8 seconds."],
  note:"Say nothing. This is a watch-and-relax video, and that's exactly why it works."},
 {id:"r8",date:"Sun 27",type:"REEL",series:"6AM 03",kids:true,film:"Sat 19 Sept",edit:"23–25 Sept",
  title:"Slow Sunday breakfast",
  what:"A slow family Sunday morning. Real sound, no talking.",
  steps:["<b>Fruit being cut on the board.</b> Close, sound on. 12 seconds.","<b>Pouring juice into glasses.</b> 8 seconds.","The table being laid — plates, napkins, flowers. 10 seconds.","<b>A small hand reaching for something.</b> Just the hand. 6 seconds.","Wide from the tripod — the table, from behind. 8 seconds."],
  note:"<b>One of only two posts this month with the children in.</b> Hands, backs and backs of heads only — never faces, never the focus. You're the main character; they're part of the room."}]},

{w:3,head:"Week 3",sub:"29 Sept – 5 Oct",note:"The formats repeat for the second time. That's what turns a set of videos into a page.",
 shoot:"<b>Thu 24 Sept</b> — course morning. <b>Sat 26 Sept</b> — main block: fit check and the long 6am film.",posts:[
 {id:"r9",date:"Tue 29",type:"REEL",series:"Studio Days 02",film:"Thu 24 Sept",edit:"26–28 Sept",
  title:"My first floor plan",
  what:"Week two at the course, first real piece of work. The progress is the story.",
  steps:["<b>The blank page, then your hand starting on it.</b> 12 seconds.","Close on <b>the ruler and pencil moving.</b> 12 seconds.","<b>The finished drawing</b>, held up or flat on the desk. 8 seconds.","Your hands tidying the pencils away. 6 seconds."],
  say:"week 2. my first floor plan.",
  note:"Short text, big effect. Anyone who saw week one stops for this because they want to know how it's going. That's what a series does."},
 {id:"c3",date:"Wed 30",type:"CAROUSEL",series:"Travel",film:"photos by 26 Sept",edit:"28 Sept",
  title:"Dubai, away from the malls",
  what:"Photos from your own phone of the parts of Dubai you actually like.",
  steps:["Send <b>eight photos of Dubai you've taken yourself</b> — quiet spots, a café, evening light, the water. Not the tourist ones.","Nothing new to shoot unless you want to."],
  note:"Place posts get saved by people planning trips, so they keep working for months. Every one of your reference pages leans on this."},
 {id:"r10",date:"Fri 2",type:"REEL",series:"Soft Life Notes 03",film:"Sat 26 Sept",edit:"29 Sept–1 Oct",
  title:"The gym was never about the body",
  what:"Your gym routine with one honest line over it. The 'strong body' half of your bio, finally on the page.",
  steps:["<b>Gym bag being packed</b> — shoes, bottle, headphones. 10 seconds.","<b>Walking in.</b> Phone low, just walk. 8 seconds.","Close on <b>your hands on the weights, or shoes on the treadmill.</b> Don't film all of yourself if you don't want to. 12 seconds.","<b>Water bottle, out of breath, mirror.</b> 8 seconds.","Walking home with a coffee. 8 seconds."],
  say:"the gym was never about the body. it was the one hour a day nobody could ask me for anything.",
  note:"The most shareable line in the month. Every mother who sees it will feel it, and a lot will send it to a friend."},
 {id:"r11",date:"Sat 3",type:"REEL",series:"Getting Ready 03",film:"Sat 26 Sept",edit:"29 Sept–1 Oct",
  title:"One outfit, built piece by piece",
  what:"An outfit coming together one item at a time. Fashion, without talking.",
  steps:["<b>The empty hanger, then the outfit going on</b> piece by piece. 15 seconds.","Close on <b>the fabric</b> — let your hand move over it. 8 seconds.","<b>Shoes going on.</b> 8 seconds.","<b>The bag picked up.</b> 6 seconds.","Final look in the mirror, turning once. 10 seconds."],
  note:"If you have three outfits you like, film all three the same way. We decide in the edit which leads."},
 {id:"r12",date:"Sun 4",type:"REEL",series:"6AM 04",film:"Sat 26 Sept",edit:"30 Sept–2 Oct",
  title:"The whole morning, start to finish",
  what:"The longest, most beautiful version of your morning. Same routine as post one — a month better.",
  steps:["<b>Curtains opening.</b> 8 seconds.","<b>Making the bed</b>, phone on the tripod. 15 seconds.","Bathroom — <b>water running, face wash.</b> 12 seconds.","The coffee, all of it — <b>kettle, pour, stir.</b> 20 seconds.","<b>Walking out to the balcony.</b> 8 seconds.","<b>The first sip</b>, city behind you. 10 seconds."],
  note:"Deliberately the same shots as the first post of the month. In a month you'll see how much better you've got — and so will everyone else."}]},

{w:4,head:"Week 4",sub:"6 – 12 Oct",note:"Closing the month: the honest one, the reflection post, the course recap.",
 shoot:"<b>Thu 1 Oct</b> — course morning. <b>Sat 3 Oct</b> — main block. Light week, mostly photos.",posts:[
 {id:"r13",date:"Tue 6",type:"REEL",series:"Soft Life Notes 04",kids:true,film:"Sat 3 Oct",edit:"4–5 Oct",
  title:"8:31am, and the house is quiet",
  what:"The school-run morning and the silence right after. The most honest post of the month.",
  steps:["<b>Two lunchboxes being closed.</b> 8 seconds.","<b>Small shoes by the front door.</b> Just the shoes. 6 seconds.","<b>A hand on the door handle</b>, door opening. 6 seconds.","From the driver's seat, <b>the drive back home.</b> 10 seconds.","<b>You sitting down alone with coffee in the quiet house.</b> Tripod, don't move it. 15 seconds."],
  say:"8:31am. the house is quiet. this is the part nobody films.",
  note:"<b>The second and last post with the children in</b>, and only their shoes and a lunchbox. Post this and read the comments — this is the kind of video that finds the exact audience you want."},
 {id:"c4",date:"Wed 7",type:"CAROUSEL",series:"Personal growth",film:"photos by 3 Oct",edit:"5 Oct",
  title:"Six things I'm unlearning",
  what:"A written post over simple images. This replaces quote graphics.",
  steps:["No filming. Send <b>six quiet photos</b> — hands, coffee, a window, your desk, anything calm.","If any of the six things are yours, tell Prince and we write them in your words."],
  note:"Real thoughts in your own words always beat a quote on a coloured background. That's why quote posts came out of the plan."},
 {id:"r14",date:"Fri 9",type:"REEL",series:"Soft Life Notes 05",film:"Sat 3 Oct",edit:"6–8 Oct",
  title:"Sunday-night reset for the week",
  what:"The night-before routine. Calm, low light, one line over the top.",
  steps:["<b>Clothes laid out for tomorrow.</b> 10 seconds.","<b>Kitchen being wiped down</b>, lights low. 10 seconds.","<b>Phone going face-down on the table.</b> 6 seconds.","<b>A book and a lamp.</b> 8 seconds.","Lamp switching off. 4 seconds."],
  say:"sunday night me is just monday morning me, doing her a favour.",
  note:"<b>This is the flexible slot.</b> If you travel or go out this month, we swap this reel for whatever you actually got."},
 {id:"c5",date:"Sat 10",type:"CAROUSEL",series:"Month one recap",film:"photos by 3 Oct",edit:"8 Oct",
  title:"One month of design school",
  what:"Everything from the course so far, in one post. The month's milestone.",
  steps:["Photograph <b>every sketch and piece of work</b> so far. One each, flat on the table, daylight.","One photo of your desk or the studio.","One of you there, if you're comfortable."],
  note:"Milestone posts beat ordinary posts on all six pages we studied. This one also sets up month two."},
 {id:"r15",date:"Sun 11",type:"REEL",series:"6AM 05",vo:true,film:"Sat 3 Oct",edit:"8–10 Oct",
  title:"One month in",
  what:"The morning ritual one last time, with a short voiceover looking back.",
  steps:["<b>Film the same morning routine as post one</b> — curtains, bed, coffee, balcony. You'll notice you're much better at it now.","Record a short voiceover at home. Under 30 seconds."],
  say:"A month ago I'd never made a video in my life. I still wake up at six, I still make the same coffee. The only thing that changed is that I stopped waiting to feel ready.",
  note:"The post that turns four weeks of content into a story with a beginning and an end. Also the strongest thing we can show anyone who asks what we do."}]},

{w:5,head:"Buffer",sub:"13 – 14 Oct",note:"Two spare days. Nothing scheduled on purpose.",
 shoot:"No shoot. These days exist so nothing is ever rushed.",posts:[
 {id:"b1",date:"Tue 13",type:"PHOTO",series:"Flexible",film:"—",edit:"—",
  title:"Photo post — whatever actually happened",
  what:"A dinner, a trip, a party. Only if there was one.",
  steps:["Nothing planned. If you took photos somewhere this month you liked, send them.","If not, we skip it. An empty slot beats a filler post."],
  note:"Every calendar needs slack. If any post above slipped, it lands here instead."},
 {id:"b2",date:"Wed 14",type:"REVIEW",series:"Month close",film:"—",edit:"—",
  title:"Month one review",
  what:"Prince pulls the numbers on all 20 posts and we decide what month two doubles down on.",
  steps:["Nothing for you to do.","You get a short summary: what worked, what didn't, what we do more of next month."],
  note:"Then the next 30 days go up on this same link — 15 Oct to 14 Nov."}]}
];
